name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "Hello!"
      - name: bye
        run: echo "Done - bye!"
